### ISSUE TITLE
Page titles jumbled at bottom of page toolbar

### ISSUE THREAD

**Issue by tsansom** [justas-d/roll20-enhancement-suite#179]
In the last few days the page toolbar fails to display the names of the pages properly

![image](https://user-images.githubusercontent.com/28094529/101173323-fcddd700-3607-11eb-8464-daad72192561.png)

I've switched back to the original page toolbar for now - did it change? I've been using VTTES for so long I don't remember what it looked like.

**Comment by Stormeal** [comment]
Thanks, works for me now :)
