### ISSUE TITLE
New Token Bug with Roll20 Update

### ISSUE THREAD

**Issue by AlexKu95** [justas-d/roll20-enhancement-suite#184]
With the Update for Roll20 from the Feburary 16,2021(I think it is the low light brightness option, See source) the tokens are bugged now.
When the token settings are saved it throws the following error (see Appendix A) and the token will no longer be updated if moved or edited. So other user can't see changes for the token.

To replicate the bug:
- Create a token from an image or drop one from the Art Library
- Open the token Editor and change anything or nothing(for example the name)
- Press the Save Settings button
- The Console will show the error(Appendix A)
- The token is no longer updated for other users

PS:
- The Bug does not occur if the character token menu is used to change the token
- This was tested under Firefox Version 86.0 (64-bit) Windows

Source: https://help.roll20.net/hc/en-us/articles/360037772613-Change-Log

Appendix A:
Uncaught Error: Firebase.update failed: First argument contains undefined in property 'campaign-9249579-PyB0fhWUF_dJrEHVstRzpg.graphics.page.-MNyNuTnUrHDsrV6GOeM.-MUJzZgo7r086a4aJip-.dim_light_opacity'
    hg https://app.roll20.net/assets/firebase.2.4.0.js:123
    jg https://app.roll20.net/assets/firebase.2.4.0.js:126
    Fb https://app.roll20.net/assets/firebase.2.4.0.js:28
    jg https://app.roll20.net/assets/firebase.2.4.0.js:126
    update https://app.roll20.net/assets/firebase.2.4.0.js:258
    sync https://app.roll20.net/assets/app.js?1613844256:81
    c https://app.roll20.net/assets/firebase.2.4.0.js:240
    Zb https://app.roll20.net/assets/firebase.2.4.0.js:201
    gc https://app.roll20.net/assets/firebase.2.4.0.js:52
    cc https://app.roll20.net/assets/firebase.2.4.0.js:30
    bc https://app.roll20.net/assets/firebase.2.4.0.js:29
    Qi https://app.roll20.net/assets/firebase.2.4.0.js:224
    Ib https://app.roll20.net/assets/firebase.2.4.0.js:238
    Og https://app.roll20.net/assets/firebase.2.4.0.js:240
    sync https://app.roll20.net/assets/app.js?1613844256:81
    save https://app.roll20.net/assets/base.js?1613497847:7
    modified https://app.roll20.net/assets/app.js?1613844256:616
    h https://app.roll20.net/assets/app.js?1613844256:609
    forEach https://app.roll20.net/assets/base.js?1613497847:6
    h https://app.roll20.net/assets/app.js?1613844256:609
    r https://app.roll20.net/assets/base.js?1613497847:6
    setTimeout handler*nrWrapper https://app.roll20.net/editor/:22
    debounce https://app.roll20.net/assets/base.js?1613497847:6
    424 https://app.roll20.net/assets/app.js?1613844256:609
    n https://app.roll20.net/assets/app.js?1613844256:582
    fire eval line 3 > eval line 25540 > eval:9406
    __onMouseUp https://app.roll20.net/assets/app.js?1613844256:584
    C https://app.roll20.net/assets/app.js?1613844256:614
    nrWrapper https://app.roll20.net/editor/:22

**Comment by justas-d** [comment]
Can't repro on 1.15.37, FF 86. Only breaks when I have betteR20 installed. Make sure it's not betteR20 that's causing the issue.

**Comment by AlexKu95** [comment]
Updating betterR20 fixed it. Thanks for the info.
