### ISSUE TITLE
Additional character tabs are broken

### ISSUE THREAD

**Issue by Riernar** [justas-d/roll20-enhancement-suite#186]
Hi,

Just wanted to tell that the additional tabs in journal entries (`export/overwrite`, `edit default token`, etc...) have been broken for a few days.
I suspect there's been changes in Roll20 -- while character sheets are loading, a rotating half-circle is displayed in the middle of the floating window to indicate a "load in progress". This wasn't the case before the tabs broke, so there might be other changes that were introduced simultaneously.

Interestingly, I had the problem some days ago, it went away (as well as the "loading circle") and now it's back.

Looking at my console, I could find errors coming from:
+ [here](https://github.com/justas-d/roll20-enhancement-suite/blob/bb2e4d28d7c275d69a1218fac4a258aafbdb7532/src/modules/AlternatePageToolbarMenu/Module.ts#L298)
+ [here](https://github.com/justas-d/roll20-enhancement-suite/blob/master/src/entrypoints/WebsiteBootstrap.js) (but i can't find where in WebsiteBoostrap.js, it says at `WebsiteBoostrap18:50914` but the line feeds are gone compared with the source here)
+ and [here](https://github.com/justas-d/roll20-enhancement-suite/blob/master/src/modules/SheetTabApi/Module.js) (again, this is not certain. The error is `e.firstElementChild.firstElementChild is null` but I can't find that code in the source. The console reports an error at `SheetTabApi.js:1:3332`).

Given the lasts commits, this might already be worked on, but I'm not sure, so I though I could open an issue anyway.

Good luck with the fix, and thank you again for this awesome extension !

**Comment by justas-d** [comment]
Roll20 seems to be doing some weird stuff right now with regards to the character sheets which includes flipping between whatever new system for displaying sheets and the old system.

I've already had to release 1.15.38 to address these issues and then revert the fixes in 1.15.39 as Roll20 reverted their changes. Waiting on Roll20 to stabilize whatever they're doing to avoid this ping-pong reverting of changes.

If you have to have the character sheet tabs, use either 1.15.38 or 1.15.39.

1.15.38 links:
https://github.com/justas-d/roll20-enhancement-suite/blob/master/page/r20es_1.15.38_chrome.zip
https://addons.mozilla.org/en-US/firefox/addon/roll20-enhancement-suite/versions/

**Comment by Riernar** [comment]
Thank you for the lightning fast answer ! That explains why the problem seemed so weird and intermittent.
I'll just wait until things are stable and you can adapt., there's no rush.

Thanks again for your work !

P.S. I'm leaving this issue open for whoever comes here with the same problem, feel free to close it if you prefer (or when things have stabilized)

**Comment by tomhamiltonstubber** [comment]
Does this also affect the macros tab of a character sheet? I'm using 39 and the tab on a character sheet to generate their macros is hidden.

**Comment by tomhamiltonstubber** [comment]
Is this closed because it's fixed? Because I still can't access the macro generator for any character sheets. I've updated to 1.16 so let me know if there's any other info I can get you.

**Comment by justas-d** [comment]
1.16 should fix the issue. If you're stilll having it, please go through the troubleshooting steps in the issues channel of our discord. https://discord.com/invite/pKxxvuM
