### ISSUE TITLE
Suggestion: Youtube/Google Drive Direct Links

### ISSUE THREAD

**Issue by rkeytech** [justas-d/roll20-enhancement-suite#199]
I'm using VTTES for a while now and I must say that your work @justas-d is awesome. It made my games reach god-like immersion and me and my players having so much fun in Roll20. 
### My problem. . .
My only problem is that I was looking for days to make the music section work till you helped me in Discord and told me that I can only use direct links to files. I googled for solutions and found that it's not that easy to get direct links to files to many cloud platforms like google drive, onedrive etc. So I thougth, I have to make something myself.
### My solution
1. I started working on a Python Script with the help of youtube-dl library to get direct links for videos/audio from Youtube. You can take the URL used for sharing, pipeline it throuth the script and get the direct link from the Youtube Server to use it with VTTES.
2. I'm almost done creating a script to get direct links from Google Drive. So you can upload your assets to Google Drive, like your music, maps, videos, and anything else you have to get a direct link to use it with VTTES, and then after enabling sharing you can get the direct link to it.
### My thoughts
I made and still making these scripts for my personal use but I was wondering if anyone else wants them too so I can upload them here on Github, with instructions how to use them, and of course open source so anyone can see and modify the code. I want your feedback on how to associate them somehow with VTTES so people can find them easier if they want to use them.

**Comment by justas-d** [comment]
If you're thinking of open-sourcing the scripts, we'd gladly let folks know that there's a script they can use.

I must point out that I doubt most people will go so far as using a script. The more convenient form of this may be a web app in which folks can post a link and get a direct link from there.
