### ISSUE TITLE
Constant crash after opening and updating better20 for the first time in a month. 

### ISSUE THREAD

**Issue by CodeOneYT** [justas-d/roll20-enhancement-suite#200]
Hi, I've been using better20 for about a year now, but recently when I redownloaded and updated better20, vtt, etc., it just kept crashing. I was unable to find any outstanding errors, so I'm not sure exactly what it is. Any ideas?

**Comment by justas-d** [comment]
Sorry, we don't offer support for betteR20. You'll want to head over to their discord for help.
