### ISSUE TITLE
Incompatible with Roll20 Enhanced Keyboard Shortcuts (REKS)

### ISSUE THREAD

**Issue by cogspace** [justas-d/roll20-enhancement-suite#201]
Hi there! I'm the developer of [Roll20 Enhanced Keyboard Shortcuts](https://greasyfork.org/en/scripts/434496-roll20-enhanced-keyboard-shortcuts). A user reported that REKS does not work when VTTES is installed.

It appears that REKS is not getting executed when VTTES is installed. A cursory reading of the VTTES code has not made the reason why clear to me, but it's a much bigger codebase that I am not familiar with, so I'm hoping someone more familiar can take a look and see what the issue is.

Here's the beginning of the REKS code, for reference.

```js
// ==UserScript==
...
// @match        *://app.roll20.net/editor/
// @match        *://app.roll20dev.net/editor/
...
// @run-at       document-idle
// @require      https://cdnjs.cloudflare.com/ajax/libs/jquery-simulate/1.1.1/jquery.simulate.min.js
// ==/UserScript==

(function() {
    'use strict';

    // Utilities
    const LOG = true;
    function log(...args) {
        if (LOG) console.log("[REKS]", ...args);
    }

    log("Roll20 Enhanced Keyboard Shortcuts is starting up...");
```

The above log message does not appear when VTTES is enabled. I'm guessing it's hijacking the normal startup process somehow and interfering with Tampermonkey starting REKS as a result. I have tried changing `@run-at` to `document-start` and waiting for the `DOMContentLoaded` event manually, and that does not work either.

Any help would be greatly appreciated!

**Comment by justas-d** [comment]
VTTES cancels the jQuery script requests that Roll20 issues and reinserts them later on after the page has technically 'loaded'. No surprise that there's an incompatability here!

I mocked up something that works, however it seems that the `jquery.simulate` code that's been `@require`'d causes some issues as it appears to assume that jQuery is available on startup:
![image](https://user-images.githubusercontent.com/10726335/150151000-68eb9775-9f06-4b8e-847b-4d77e580092b.png)
(the image shows pretty-printed userscript source from the Chrome console)

Here's a quick mockup, without the `jquery.simulate` require.
https://gist.github.com/justas-d/d5f5e9f08afca6e1fbcc6ba8dbe30018

For the jQuery issue, I believe that waiting on `window.jQuery` to be defined before initializing the functionality of the script should do the trick. As for the `jquery.simulate` issue, I'm not certain but I believe there are gains to be had by inlining the script and manually issuing its initialization as opposed to letting Tampermonkey decide that for you (as it appears to be deciding wrongly).

**Comment by cogspace** [comment]
Thanks a bunch! Now that I know the root cause I'm confident I can get the jquery-simulate bit working.
